# Generated by Django 5.0.6 on 2024-05-22 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roles', models.CharField(choices=[('ADMIN', 'ADMIN '), ('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER')], max_length=7)),
                ('phone', models.CharField(max_length=8)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
